# Generated by Django 5.2 on 2025-04-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Headers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("isMain", models.BooleanField()),
                ("textOne", models.TextField()),
                ("textTwo", models.TextField()),
                ("image", models.ImageField(upload_to="headerImage")),
            ],
        ),
    ]
