# Generated by Django 5.2 on 2025-04-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_headers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Headers',
            new_name='Header',
        ),
    ]
