# Generated by Django 5.2 on 2025-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_headers_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyname',
            name='year',
            field=models.CharField(default=2024, max_length=4),
            preserve_default=False,
        ),
    ]
