name: Ping https://dosojincargos.online Every 10 Minutes

on:
  schedule:
    - cron: "*/6 * * * *"  # Every 10 minutes (UTC time)
  workflow_dispatch:        # Allows manual trigger from GitHub UI

jobs:
  ping-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ping https://dosojincargos.online
        run: |
          echo "Pinging https://dosojincargos.online..."
          curl -I https://dosojincargos.online
